language: go
sudo: false
go:
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - tip
script:
  - go get -u golang.org/x/lint/golint
  - OUT="$(env GO111MODULE=on go get -a)"; test -z "$OUT" || (echo "$OUT" && return 1)
  - OUT="$(gofmt -l -d ./)"; test -z "$OUT" || (echo "$OUT" && return 1)
  - OUT="$(golint ./...)"; test -z "$OUT" || (echo "$OUT" && return 1)
  - env GO111MODULE=on go vet -v ./...
  - env GO111MODULE=on go test -race -v -coverprofile=coverage.txt -covermode=atomic ./
  - env GO111MODULE=on go build
after_success:
  - bash <(curl -s https://codecov.io/bash)
